### ISSUE TITLE
Cleanup make file 

### ISSUE THREAD

**Issue by lizliz** [lizliz/teaspoon#19]
The makefile is currently a bit messy. Here's ideally what I think I want it to do: 
- Run `make docs` to compile the documentation 
- Run `make tests` to run all the unittests
- Ruen `make clean` to run the autopep8 recursively on all files. 
- Run `make all` to do everything above 
- Run `make help` to get some sort of explanation of all these options 

Other things I'm forgetting but should be able to do? Some ideas that might be useful are
- Auto-incrementing the version number
- Updating the list of required packages in the documentation, even if we don't make the installs part of the requirement since that seems to be hella buggy and tenuous. 
- Might be helpful to have some sort of linting automatically set up. pylint seems to not like my naming conventions, but there might be better options for including this.

**Comment by barnesd8** [comment]
The following has been implemented and I am now testing:

make requirements:  replace requirements.txt file for use by collaborators and for documentation
make docs: removes current docs, rebuilds docs from source folder (still need to pull in info from requirements.txt into documentation)
make tests: runs the unittest script
make clean: run autopep8 recursively
make build: runs build to create tar and wheel for distribution
make all: does all above
make help: explains the above

This is mainly reconfigured from Audun's code and just combining some of the functions.  Once tested I'll close this and move the further requests to a new issue.
