### ISSUE TITLE
python version issues 

### ISSUE THREAD

**Issue by sarahtymochko** [lizliz/teaspoon#25]
In fighting with the other issue (#16 ) I've had to change my numpy version several times. We should specify on the documentation page if there are certain versions of packages that are needed (or certain versions that dont work). For example, the ordinal partition network test gives me a segfault with the most recent numpy version, with numpy==1.15.0 it runs but the test fails, but I assume it works for @lizliz since she setup the unittests stuff.

Also, the `sortedcontainers` package is needed in one of the tests, but it isn't on the list in the documentation of things that are needed to pip install.

**Comment by barnesd8** [comment]
This is related to this issue ([https://github.com/lizliz/teaspoon/issues/42]), and versions should automatically install with teaspoon install at next release.  Dependences for os, sys, and itertools likely need removed from documentation page also.

**Comment by barnesd8** [comment]
Completed and merged into version 1.3.1
