### ISSUE TITLE
Cleanup ML setup

### ISSUE THREAD

**Issue by lizliz** [lizliz/teaspoon#32]
I want to figure out if its possible to cleanup the ML code bank to be relatively uniform across choices of featurizations. 

Big issue is that the tent functions don't show up at all in the documentation, so that's already very problematic, but that's already in its own issue  #17 

However, organizationally what I'd like to see is if variants of the code below with only minor modifications could be used for running persistence images or landscapes or whatever. I'm not sure if this involves a ton of new code, but might mean that some rewriting of documentation would be useful. 
```
import teaspoon.ML.Base as Base
import teaspoon.MakeData.PointCloud as gPC
import teaspoon.ML.feature_functions as fF
from sklearn.linear_model import RidgeClassifierCV

params = Base.TentParameters(clf_model = RidgeClassifierCV,
                             feature_function = fF.tent,
                              test_size = .33,
                              seed = 48824,
                              d = 10,
                              delta = 1,
                              epsilon = 0
                             )

DgmsDF = gPC.testSetClassification(N = 20,
                                  numDgms = 50,
                                  muRed = (1,3),
                                  muBlue = (2,5),
                                  sd = 1,
                                   seed = 48824
                                  )

out = Base.getPercentScore(DgmsDF,dgm_col = 'Dgm', labels_col = 'trainingLabel', params = params )
```

**Comment by mcanyesilli** [comment]
The setup is cleaned. For more detail, please see #34
