### ISSUE TITLE
value for a variable in feature_landscape

### ISSUE THREAD

**Issue by waqarshah786** [lizliz/teaspoon#58]
I am trying to get a feature matrix (let suppose for first 10 persistent landscapes). My question is, what value should be given to variable params in F_Landscape function?? As for me, I give a value for desired landscape (lets say params = 5 ) its make an error. Need help

**Comment by mcanyesilli** [comment]
`params` represents the parameter bucket object. You can refer the example here how to use the function for feature matric generation.

`import numpy as np
from teaspoon.MakeData.PointCloud import testSetManifolds
from teaspoon.ML import feature_functions as Ff
from teaspoon.ML.Base import ParameterBucket

# generate persistence diagrams
df = testSetManifolds(numDgms = 50, numPts = 100)
Diagrams_H1 = df['Dgm1']
# Compute the persistence landscapes
PL = np.ndarray(shape=(len(Diagrams_H1)), dtype=object)
for i in range(len(Diagrams_H1)):
    lps =Ff.PLandscape(Diagrams_H1[i])
    PL[i] = lps.AllPL
# create the parameter bucket object
params = ParameterBucket()
params.feature_function = Ff.F_Landscape
params.PL_Number = [1,2,3,4,5]
params.k_fold_cv=5
# compute the features
features,mesh = Ff.F_Landscape(PL, params, max_l_number=None)`

Please let us know if you run into further issues. 
Thanks,
Melih
